### PR TITLE
Fix for better diagrams

### PR DESCRIPTION
**Pull request by rowleya**
Needed by SpiNNakerManchester/PACMAN#436 but only when the config option is enabled

### CODE REVIEW

**Comment by rowleya** [comment]
Looks like there are some whitespace changes too.  See below for non-whitespace link:
https://github.com/SpiNNakerManchester/SpiNNer/pull/8/files?diff=split&w=1

**Comment by mossblaser** [comment]
Do you have any samples of the new diagrams? (Always nice to see how things are going in SpiNNaker land all these years later!)

Hope all is well and sending all the best!

**Comment by rowleya** [comment]
> Do you have any samples of the new diagrams? (Always nice to see how things are going in SpiNNaker land all these years later!)

The only real changes here are:
1) Allow the chips to be coloured
2) Allow drawing of non-wrapped boards

Example of the placement of the microcircuit during debugging: 
tmpxz9zak_3 rpt

**Comment by mossblaser** [comment]
That's really cool! (Also what a big simulation!)

If it's of any use I don't know if you remember this tool: https://github.com/project-rig/rig-par-diagram It's a little rig-oriented but might be useful if you ever want routing information (or core-level info).

**Comment by rowleya** [comment]
> If it's of any use I don't know if you remember this tool: https://github.com/project-rig/rig-par-diagram It's a little rig-oriented but might be useful if you ever want routing information (or core-level info).

I had forgotten that one, but will definitely look it up - thanks!

**Pull request merged**
